// lib/pdf.ts — client-side PDF progress report (jsPDF).
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import {
  Entry,
  Settings,
  Unit,
  toDisplay,
  round1,
  dailySeries,
  movingAverage,
  summarize,
} from "./stats";
import {
  Workout,
  exerciseNames,
  exerciseProgression,
  personalRecords,
  exerciseSessions,
  workoutVolume,
  muscleVolume,
  avgWorkoutsPerWeek,
  weekStreak,
  MUSCLE_LABELS,
} from "./workouts";

const INK = "#131824";
const MUTED = "#6a7488";
const ACCENT = "#0fb7a4";
const ACCENT2 = "#5b63e0";
const WARN = "#d67d2c";
const LINE = "#e2e6ee";
const SOFT = "#f4f6f9";

const PAGE_W = 595.28;
const PAGE_H = 841.89;
const M = 42; // margin

function hexToRgb(h: string): [number, number, number] {
  const n = parseInt(h.slice(1), 16);
  return [(n >> 16) & 255, (n >> 8) & 255, n & 255];
}
function setFill(doc: jsPDF, hex: string) {
  const [r, g, b] = hexToRgb(hex);
  doc.setFillColor(r, g, b);
}
function setStroke(doc: jsPDF, hex: string) {
  const [r, g, b] = hexToRgb(hex);
  doc.setDrawColor(r, g, b);
}
function setText(doc: jsPDF, hex: string) {
  const [r, g, b] = hexToRgb(hex);
  doc.setTextColor(r, g, b);
}
function fmtDate(ts: number): string {
  return new Date(ts).toLocaleDateString(undefined, {
    day: "numeric",
    month: "short",
    year: "numeric",
  });
}
function fmtShort(ts: number): string {
  return new Date(ts).toLocaleDateString(undefined, { day: "numeric", month: "short" });
}

interface Pt {
  t: number;
  v: number;
}
interface Series {
  points: Pt[];
  color: string;
  width?: number;
  dash?: number[];
}

function drawLineChart(
  doc: jsPDF,
  x: number,
  y: number,
  w: number,
  h: number,
  series: Series[],
  unit: string
) {
  const all = series.flatMap((s) => s.points);
  if (all.length === 0) return;
  const pad = 30;
  const plotX = x + pad;
  const plotY = y + 6;
  const plotW = w - pad - 8;
  const plotH = h - 22;
  const plotBottom = plotY + plotH;

  const ts = all.map((p) => p.t);
  const vs = all.map((p) => p.v);
  let tMin = Math.min(...ts);
  let tMax = Math.max(...ts);
  let vMin = Math.min(...vs);
  let vMax = Math.max(...vs);
  if (tMax === tMin) tMax = tMin + 1;
  const vpad = Math.max(0.5, (vMax - vMin) * 0.12);
  vMin -= vpad;
  vMax += vpad;
  if (vMax === vMin) vMax = vMin + 1;

  const px = (t: number) => plotX + ((t - tMin) / (tMax - tMin)) * plotW;
  const py = (v: number) => plotBottom - ((v - vMin) / (vMax - vMin)) * plotH;

  // background
  setFill(doc, SOFT);
  doc.roundedRect(x, y, w, h, 4, 4, "F");

  // gridlines + y labels
  doc.setFontSize(7);
  setText(doc, MUTED);
  setStroke(doc, LINE);
  doc.setLineWidth(0.5);
  for (let i = 0; i <= 3; i++) {
    const v = vMin + ((vMax - vMin) * i) / 3;
    const gy = py(v);
    doc.line(plotX, gy, plotX + plotW, gy);
    doc.text(`${Math.round(v)}`, plotX - 4, gy + 2, { align: "right" });
  }
  // x labels
  doc.text(fmtShort(tMin), plotX, plotBottom + 12);
  doc.text(fmtShort(tMax), plotX + plotW, plotBottom + 12, { align: "right" });

  // series
  for (const s of series) {
    if (s.points.length === 0) continue;
    setStroke(doc, s.color);
    doc.setLineWidth(s.width ?? 1.5);
    if (s.dash) doc.setLineDashPattern(s.dash, 0);
    else doc.setLineDashPattern([], 0);
    const sorted = [...s.points].sort((a, b) => a.t - b.t);
    for (let i = 1; i < sorted.length; i++) {
      doc.line(px(sorted[i - 1].t), py(sorted[i - 1].v), px(sorted[i].t), py(sorted[i].v));
    }
  }
  doc.setLineDashPattern([], 0);
  // unit label
  doc.setFontSize(7);
  setText(doc, MUTED);
  doc.text(unit, x + w - 4, y + 10, { align: "right" });
}

function footer(doc: jsPDF, page: number) {
  setText(doc, MUTED);
  doc.setFontSize(8);
  doc.text("Generated by Mercury", M, PAGE_H - 20);
  doc.text(`${page}`, PAGE_W - M, PAGE_H - 20, { align: "right" });
}

export function generateReport(
  entries: Entry[],
  workouts: Workout[],
  settings: Settings | null,
  unit: Unit
) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const name = settings?.name || "Athlete";
  let page = 1;

  // ---------- Header band ----------
  setFill(doc, INK);
  doc.rect(0, 0, PAGE_W, 92, "F");
  setFill(doc, ACCENT);
  doc.circle(M + 6, 40, 7, "F");
  setText(doc, "#ffffff");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("Mercury", M + 22, 46);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  setText(doc, "#b6bece");
  doc.text("Progress Report", M + 22, 62);
  doc.setFontSize(9);
  doc.text(fmtDate(Date.now()), PAGE_W - M, 40, { align: "right" });
  doc.text(name, PAGE_W - M, 56, { align: "right" });

  let y = 118;
  const s = summarize(entries);
  const daily = dailySeries(entries);
  const firstTs = daily.length ? daily[0].ts : Date.now();
  const lastTs = daily.length ? daily[daily.length - 1].ts : Date.now();
  const weeks = Math.max(1, (lastTs - firstTs) / (7 * 86400000));
  const rate = s.totalChange != null ? s.totalChange / weeks : 0;

  // date range
  setText(doc, MUTED);
  doc.setFontSize(9.5);
  if (daily.length)
    doc.text(`Weight data: ${fmtDate(firstTs)} — ${fmtDate(lastTs)}`, M, y);
  y += 18;

  // ---------- KPI cards ----------
  const kpis: { label: string; value: string; color?: string }[] = [
    {
      label: `Current (${unit})`,
      value: s.current != null ? `${round1(toDisplay(s.current, unit))}` : "—",
    },
    {
      label: `Change (${unit})`,
      value:
        s.totalChange != null
          ? `${s.totalChange <= 0 ? "" : "+"}${round1(toDisplay(s.totalChange, unit))}`
          : "—",
      color: s.totalChange != null && s.totalChange <= 0 ? ACCENT : WARN,
    },
    {
      label: `Rate (${unit}/wk)`,
      value: `${rate <= 0 ? "" : "+"}${round1(toDisplay(rate, unit))}`,
      color: rate <= 0 ? ACCENT : WARN,
    },
    { label: "Workouts", value: `${workouts.length}` },
    { label: "Exercises", value: `${exerciseNames(workouts).length}` },
  ];
  const gap = 10;
  const cw = (PAGE_W - M * 2 - gap * (kpis.length - 1)) / kpis.length;
  kpis.forEach((k, i) => {
    const kx = M + i * (cw + gap);
    setFill(doc, SOFT);
    doc.roundedRect(kx, y, cw, 54, 5, 5, "F");
    setText(doc, k.color || INK);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(15);
    doc.text(k.value, kx + cw / 2, y + 26, { align: "center" });
    setText(doc, MUTED);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    doc.text(k.label.toUpperCase(), kx + cw / 2, y + 42, { align: "center" });
  });
  y += 74;

  // ---------- Weight chart ----------
  setText(doc, INK);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("Weight progression", M, y);
  y += 8;
  if (daily.length > 1) {
    const actual = daily.map((d) => ({ t: d.ts, v: toDisplay(d.kg, unit) as number }));
    const ma = movingAverage(entries, 7).map((m) => ({
      t: m.ts,
      v: toDisplay(m.avg, unit) as number,
    }));
    drawLineChart(
      doc,
      M,
      y,
      PAGE_W - M * 2,
      170,
      [
        { points: actual, color: ACCENT, width: 1, dash: undefined },
        { points: ma, color: ACCENT2, width: 2 },
      ],
      unit
    );
    y += 178;
    // legend
    doc.setFontSize(8);
    setFill(doc, ACCENT);
    doc.rect(M, y - 6, 8, 3, "F");
    setText(doc, MUTED);
    doc.text("daily", M + 12, y - 3);
    setFill(doc, ACCENT2);
    doc.rect(M + 50, y - 6, 8, 3, "F");
    doc.text("7-day average", M + 62, y - 3);
    y += 14;
  } else {
    setText(doc, MUTED);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9.5);
    doc.text("Not enough weight readings yet.", M, y + 16);
    y += 30;
  }

  // ---------- Milestones table ----------
  const goalKg = settings?.goalKg ?? null;
  const rows: string[][] = [
    ["Start", s.start != null ? `${round1(toDisplay(s.start, unit))} ${unit}` : "—"],
    ["Current", s.current != null ? `${round1(toDisplay(s.current, unit))} ${unit}` : "—"],
    ["Lowest", s.min != null ? `${round1(toDisplay(s.min, unit))} ${unit}` : "—"],
    ["Highest", s.max != null ? `${round1(toDisplay(s.max, unit))} ${unit}` : "—"],
    [
      "Total change",
      s.totalChange != null
        ? `${s.totalChange <= 0 ? "" : "+"}${round1(toDisplay(s.totalChange, unit))} ${unit}`
        : "—",
    ],
    ["Avg rate", `${rate <= 0 ? "" : "+"}${round1(toDisplay(rate, unit))} ${unit}/week`],
  ];
  if (goalKg != null)
    rows.push(["Goal", `${round1(toDisplay(goalKg, unit))} ${unit}`]);

  autoTable(doc, {
    startY: y,
    head: [["Milestone", "Value"]],
    body: rows,
    theme: "grid",
    styles: { fontSize: 9, cellPadding: 5, lineColor: hexToRgb(LINE), textColor: hexToRgb(INK) },
    headStyles: { fillColor: hexToRgb(INK), textColor: [255, 255, 255], fontSize: 9 },
    alternateRowStyles: { fillColor: hexToRgb(SOFT) },
    margin: { left: M, right: M },
    tableWidth: (PAGE_W - M * 2) / 2 - 5,
  });

  footer(doc, page);

  // ---------- Progressive overload ----------
  const names = exerciseNames(workouts);
  const prs = personalRecords(workouts);

  if (names.length) {
    doc.addPage();
    page++;
    let ey = M + 6;
    setText(doc, INK);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(15);
    doc.text("Progressive overload", M, ey);
    ey += 8;
    setText(doc, MUTED);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.text("Estimated 1RM progression per exercise, oldest to latest.", M, ey + 8);
    ey += 26;

    const blockH = 150;
    for (const nm of names) {
      const prog = exerciseProgression(workouts, nm);
      if (!prog.length) continue;
      if (ey + blockH > PAGE_H - 44) {
        footer(doc, page);
        doc.addPage();
        page++;
        ey = M + 6;
      }
      const pr = prs.get(nm.trim().toLowerCase());
      const first1 = prog[0].best1RM;
      const last1 = prog[prog.length - 1].best1RM;
      const delta = last1 - first1;

      // title
      setText(doc, INK);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(11.5);
      doc.text(nm, M, ey);
      // stat line
      setText(doc, MUTED);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8.5);
      const statLine = [
        `${prog.length} sessions`,
        `1RM ${round1(toDisplay(first1, unit))}→${round1(toDisplay(last1, unit))} ${unit}`,
        `${delta >= 0 ? "+" : ""}${round1(toDisplay(delta, unit))} ${unit}`,
        pr ? `best ${round1(toDisplay(pr.best1RM, unit))} ${unit}` : "",
      ]
        .filter(Boolean)
        .join("   •   ");
      doc.text(statLine, M, ey + 13);

      // delta badge
      setText(doc, delta >= 0 ? ACCENT : WARN);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(11);
      doc.text(
        `${delta >= 0 ? "▲" : "▼"} ${Math.abs(round1(toDisplay(delta, unit)) ?? 0)} ${unit}`,
        PAGE_W - M,
        ey,
        { align: "right" }
      );

      // chart
      const pts = prog.map((p) => ({ t: p.ts, v: toDisplay(p.best1RM, unit) as number }));
      drawLineChart(doc, M, ey + 20, PAGE_W - M * 2, blockH - 30, [
        { points: pts, color: ACCENT, width: 1.6 },
      ], unit);
      ey += blockH + 10;
    }
    footer(doc, page);
  }

  // ---------- Training summary ----------
  if (workouts.length) {
    doc.addPage();
    page++;
    let ty = M + 6;
    setText(doc, INK);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(15);
    doc.text("Training summary", M, ty);
    ty += 22;

    const totalVol = workouts.reduce((a, w) => a + workoutVolume(w), 0);
    const sumRows: string[][] = [
      ["Total workouts", `${workouts.length}`],
      ["Avg workouts / week", `${Math.round(avgWorkoutsPerWeek(workouts, 8) * 10) / 10}`],
      ["Current week streak", `${weekStreak(workouts)}`],
      ["Total volume", `${Math.round(toDisplay(totalVol, unit) ?? 0).toLocaleString()} ${unit}`],
    ];
    autoTable(doc, {
      startY: ty,
      head: [["Metric", "Value"]],
      body: sumRows,
      theme: "grid",
      styles: { fontSize: 9, cellPadding: 5, lineColor: hexToRgb(LINE), textColor: hexToRgb(INK) },
      headStyles: { fillColor: hexToRgb(INK), textColor: [255, 255, 255] },
      alternateRowStyles: { fillColor: hexToRgb(SOFT) },
      margin: { left: M, right: M },
    });
    ty = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 24;

    // Muscle volume
    const mv = muscleVolume(workouts, 3650);
    if (mv.length) {
      setText(doc, INK);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(12);
      doc.text("Volume by muscle group", M, ty);
      ty += 8;
      autoTable(doc, {
        startY: ty,
        head: [["Muscle", "Sets", `Volume (${unit})`]],
        body: mv
          .sort((a, b) => b.volume - a.volume)
          .map((m) => [
            MUSCLE_LABELS[m.muscle],
            `${m.sets}`,
            `${Math.round(toDisplay(m.volume, unit) ?? 0).toLocaleString()}`,
          ]),
        theme: "grid",
        styles: { fontSize: 9, cellPadding: 5, lineColor: hexToRgb(LINE), textColor: hexToRgb(INK) },
        headStyles: { fillColor: hexToRgb(ACCENT), textColor: [255, 255, 255] },
        alternateRowStyles: { fillColor: hexToRgb(SOFT) },
        margin: { left: M, right: M },
      });
      ty = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 24;
    }

    // PR highlights
    const prRows = names
      .map((nm) => {
        const pr = prs.get(nm.trim().toLowerCase());
        if (!pr) return null;
        return [
          nm,
          `${round1(toDisplay(pr.best1RM, unit))} ${unit}`,
          `${round1(toDisplay(pr.bestWeight, unit))}×${pr.bestWeightReps}`,
          fmtShort(pr.best1RMTs),
        ];
      })
      .filter((r): r is string[] => r != null);
    if (prRows.length) {
      if (ty + 60 > PAGE_H - 44) {
        footer(doc, page);
        doc.addPage();
        page++;
        ty = M + 6;
      }
      setText(doc, INK);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(12);
      doc.text("Personal records", M, ty);
      ty += 8;
      autoTable(doc, {
        startY: ty,
        head: [["Exercise", "Best 1RM", "Heaviest set", "Since"]],
        body: prRows,
        theme: "grid",
        styles: { fontSize: 9, cellPadding: 5, lineColor: hexToRgb(LINE), textColor: hexToRgb(INK) },
        headStyles: { fillColor: hexToRgb(WARN), textColor: [255, 255, 255] },
        alternateRowStyles: { fillColor: hexToRgb(SOFT) },
        margin: { left: M, right: M },
      });
    }
    footer(doc, page);
  }

  doc.save(`mercury-report-${new Date().toISOString().slice(0, 10)}.pdf`);
}
